EM-2040 i2c fixes DO NOT MERGE
Ultimaker/linux pull request #2
Opened 2018-02-12 08:29 UTC by oliv3r

For review purposes only!

2018-02-12 08:35 UTC, MarcoTvM commented on arch/arm/boot/dts/sun7i-a20.dtsi
> +			#clock-cells = <0>;
Commented out does not need to be checked in

2018-02-12 08:35 UTC, MarcoTvM commented on arch/arm/boot/dts/sun7i-a20.dtsi
> +			#size-cells = <0>;
Commented out does not need to be checked in

2018-02-12 08:35 UTC, MarcoTvM commented on arch/arm/boot/dts/sun7i-a20.dtsi
> +			#address-cells = <1>;
Commented out does not need to be checked in

2018-02-12 08:39 UTC, MarcoTvM commented on drivers/gpu/drm/sun4i/sun4i_hdmi_ddc_clk.c
> +	const char *parents[SUN4I_HDMI_I2C_CLK_NUM_PARENTS];
This creates a local (on stack) array of 1 character (define is 1), yet, this is being passed on indirectly as a pointer to other places using structures. See comment further on.

2018-02-12 08:40 UTC, MarcoTvM commented on drivers/gpu/drm/sun4i/sun4i_hdmi_ddc_clk.c
> +	parents[0] = __clk_get_name(parent_clk);
Filling the actual value here, in original code, you get a char pointer

2018-02-12 08:41 UTC, MarcoTvM commented on drivers/gpu/drm/sun4i/sun4i_hdmi_ddc_clk.c
> +	init.parent_names = parents;
This should be &parents[0]?
Should parents be made static?

2018-02-12 08:49 UTC, MarcoTvM commented on drivers/gpu/drm/sun4i/sun4i_hdmi_i2c_drv.c
> +					   reg, !reg, 100, 2000))
introduce defines that describe what 100 and 2000 mean?
seconds? milisecond? usec?

2018-02-12 08:49 UTC, MarcoTvM commented on drivers/gpu/drm/sun4i/sun4i_hdmi_i2c_drv.c
> +					   100000))
introduce define to make clear what this magical number means

2018-02-12 08:51 UTC, MarcoTvM commented on drivers/gpu/drm/sun4i/sun4i_hdmi_i2c_drv.c
> +					   reg, !reg, 100, 100000))
More of the same, magical values!

2018-02-12 08:54 UTC, MarcoTvM requested changes
Mostly magical numbers, but one issue with pointers that worries me.

2018-03-01 11:10 UTC, oliv3r commented
New PR #4

2018-03-01 11:10 UTC, closed without merging